# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  build:
    docker:
      - image: continuumio/miniconda3

    steps:
      - checkout
      
      - run
        name: install
        command: |
          conda env update --file genusfinder_env.yaml
          python -m pip install --upgrade pip
          python -m pip install pytest
          python -m pip install .
        
      - run
        name: run tests
        command: pytest -vvl tests/
